// <auto-generated />
using System;
using EnterpriseBilling.UI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseBilling.UI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531231358_CorreccionForeignKeyDetails")]
    partial class CorreccionForeignKeyDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EnterpriseBilling.UI.Models.Bill", b =>
                {
                    b.Property<int>("IdBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTaxes")
                        .HasColumnType("TEXT");

                    b.HasKey("IdBill");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.BillDetail", b =>
                {
                    b.Property<int>("IdBillDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillIdBill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdBill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProduct")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PercentTaxes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductIdProduct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("IdBillDetail");

                    b.HasIndex("BillIdBill");

                    b.HasIndex("ProductIdProduct");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "xxx@xxx.com",
                            Name = "end consumer",
                            Phone = "000000000"
                        });
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdProduct");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            Barcode = "101010",
                            Cost = 20m,
                            NameProduct = "KeyBoard RGB",
                            SalePrice = 24.50m,
                            Stock = 20
                        },
                        new
                        {
                            IdProduct = 2,
                            Barcode = "202020",
                            Cost = 10m,
                            NameProduct = "Mouse RGB",
                            SalePrice = 14.50m,
                            Stock = 20
                        },
                        new
                        {
                            IdProduct = 3,
                            Barcode = "303030",
                            Cost = 11m,
                            NameProduct = "Windows licences",
                            SalePrice = 12.8m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.TaxesType", b =>
                {
                    b.Property<int>("IdTaxesType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameTaxes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percent")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTaxesType");

                    b.ToTable("TaxesTypes");

                    b.HasData(
                        new
                        {
                            IdTaxesType = 1,
                            NameTaxes = "Exento de Impuestos",
                            Percent = 0m
                        },
                        new
                        {
                            IdTaxesType = 2,
                            NameTaxes = "GST/IVA (18%)",
                            Percent = 18m
                        },
                        new
                        {
                            IdTaxesType = 3,
                            NameTaxes = "IVA (13%)",
                            Percent = 13m
                        });
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Activo = false,
                            Password = "123",
                            Rol = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.Bill", b =>
                {
                    b.HasOne("EnterpriseBilling.UI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnterpriseBilling.UI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.BillDetail", b =>
                {
                    b.HasOne("EnterpriseBilling.UI.Models.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillIdBill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseBilling.UI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductIdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EnterpriseBilling.UI.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
